# Generated by Django 4.2 on 2026-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Short caption (optional)', max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('shop', 'Our shop'), ('phones', 'Phones'), ('repairs', 'Repairs'), ('accessories', 'Accessories'), ('other', 'Other')], default='phones', max_length=20)),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide without deleting')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
